services:
  api:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - API_KEY=${API_KEY}
      - MODEL=${MODEL:-gemini-2.0-flash}
      - BASE_URL=${BASE_URL}
    volumes:
      - .:/code
    restart: unless-stopped
    command: >
      sh -c "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"